flowchart TB
    subgraph AC[Airport creation]
        A[List of airports]
        B[Admin]
        C[Add site]
        D[Airport added]
        E[Go to airport]
    end

    A --> B
    B --> C
    C --> D
    D --> E